### 1. Criar um array com 10 números inteiros aleatórios entre 1 e 50 e calcular a média e o desvio padrão

In [0]:
import numpy as np

In [0]:
arr= np.random.randint(1,51,size=10)
print(arr)

[21 19 28  7 47  4 38  4 12  8]


In [0]:
media= np.mean(arr)
desvio= np.std(arr)

print(arr)
print("Média: ",media)
print("Desvio: ",desvio)

[21 19 28  7 47  4 38  4 12  8]
Média:  18.8
Desvio:  14.119490075778232


### 2. Criar um array de 10 números aleatórios e calcular a raiz quadrada de todos os valores menores ou iguais a 0,5

In [0]:
arr= np.random.rand(10)

arr[arr<= 0.5]= np.sqrt(arr[arr <=0.5])
print(arr)

[0.41983627 0.57777966 0.50187044 0.65147594 0.53108011 0.95025737
 0.82866216 0.69584607 0.58470942 0.59724877]


### 3. Criar uma matriz 3D de tamanho 3x3x3 com valores aleatórios e exibir o valor máximo de cada linha de cada matriz 2D dentro dessa matriz 3D

In [0]:
matriz= np.random.rand(3,3,3)

resul= np.amax(matriz,axis=1)
print("Matriz criada " , matriz)
print("Resultado " , resul)

Matriz criada  [[[0.60109016 0.43560326 0.25772211]
  [0.43654665 0.80352193 0.43324573]
  [0.22158162 0.44982236 0.71988087]]

 [[0.19455583 0.9007881  0.81543841]
  [0.94834976 0.28372425 0.36273575]
  [0.557189   0.41509782 0.63560975]]

 [[0.14407143 0.3023499  0.32306991]
  [0.53225852 0.81669131 0.28444106]
  [0.52539318 0.38459284 0.1590776 ]]]
Resultado  [[0.60109016 0.80352193 0.71988087]
 [0.94834976 0.9007881  0.81543841]
 [0.53225852 0.81669131 0.32306991]]


### 4. Criar uma matriz de tamanho 5x5 com valores aleatórios e subtrair a média de cada linha dessa matriz

In [0]:
arr= np.random.rand(5,5)

media= np.mean(arr,axis= 1)
sub= arr - media[:,np.newaxis]

print("Array: ",arr)
print("Resultado ",sub)


Array:  [[0.70811795 0.41656308 0.49245317 0.73121336 0.72703373]
 [0.55108962 0.74871678 0.82774352 0.66992673 0.68909902]
 [0.09358155 0.89861915 0.52236653 0.43835057 0.39920784]
 [0.48230454 0.61098832 0.09736782 0.0642002  0.49084504]
 [0.43188721 0.67929666 0.66870501 0.84143802 0.37944011]]
Resultado  [[ 0.0930417  -0.19851318 -0.12262308  0.1161371   0.11195747]
 [-0.14622552  0.05140165  0.13042839 -0.0273884  -0.00821612]
 [-0.37684357  0.42819402  0.0519414  -0.03207456 -0.07121729]
 [ 0.13316336  0.26184713 -0.25177337 -0.28494098  0.14170386]
 [-0.16826619  0.07914326  0.06855161  0.24128462 -0.22071329]]


### 5. Criar uma matriz de tamanho 4x4 com valores aleatórios e calcular a média e o desvio padrão das diagonais da matriz

In [0]:
arr= np.random.rand(4,4)

print(arr)

[[0.76880372 0.04017209 0.76443011 0.93261056]
 [0.26083231 0.33074389 0.05455724 0.85704446]
 [0.21688667 0.20872198 0.33964928 0.2086061 ]
 [0.56149599 0.37920846 0.76668238 0.15543638]]


In [0]:
media_1= np.mean(np.diagonal(arr))
desvio_1= np.std(np.diagonal(arr))
print("Media: ",media_1)
print("Desvio: ",desvio_1)

Media:  0.3986583193071232
Desvio:  0.2259750904962828


In [0]:
media_2= np.mean(np.diagonal(np.fliplr(arr)))
desvio_2= np.std(np.diagonal(np.fliplr(arr)))

print("Media_inverso: ",media_2)
print("Desvio_inverso: ",desvio_2)

Media_inverso:  0.43934644274448753
Desvio_inverso:  0.33892491039190925
